const usersTypes = {
	GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
	USER_SELECTION_SUCCESS: 'USER_SELECTION_SUCCESS',
	CHANGE_USER_ROLE_SUCCESS: 'SAVE_PROFILE_SUCCESS',
	ROLE_ASSIGN_CANCELED: 'ROLE_ASSIGN_CANCELED',
	NEW_ROLE_SELECTION_SUCCESS: 'NEW_ROLE_SELECTION_SUCCESS',
};

export default usersTypes;
