export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const ERROR = 'ERROR';
export const VALIDATION_ERRORS = 'VALIDATION_ERRORS';
export const BUTTON_LOADING = 'BUTTON_LOADING';
export const LOADING = 'LOADING';
export const TOAST = 'TOAST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const GET_MANAGER_REQUESTS_SUCCESS = 'GET_MANAGER_REQUESTS_SUCCESS';
export const GET_MANAGER_REQUESTS_FAIL = 'GET_MANAGER_REQUESTS_FAIL';
export const GET_ONE_MANAGER_REQUEST_SUCCESS =
	'GET_ONE_MANAGER_REQUEST_SUCCESS';
export const GET_ONE_MANAGER_REQUEST_FAIL = 'GET_ONE_MANAGER_REQUEST__FAIL';
