export const profileFields = [
	{
		id: 1,
		placeholder: 'Enter First Name',
		name: 'firstName',
		type: 'text',
		label: 'First Name',
		required: true,
		error: 'firstNameError',
	},
	{
		id: 2,
		placeholder: 'Enter Last Name',
		name: 'lastName',
		type: 'text',
		label: 'Last Name',
		required: true,
		error: 'lastNameError',
	},
	{
		id: 3,
		placeholder: 'Select Date',
		name: 'birthDate',
		type: 'date',
		label: 'Date of Birth',
		required: true,
		error: 'birthDateError',
	},
	{
		id: 4,
		placeholder: 'Enter Department',
		name: 'department',
		type: 'text',
		label: 'department',
		required: true,
		error: 'departmentError',
	},
	{
		id: 5,
		placeholder: 'Enter Email',
		name: 'email',
		type: 'email',
		label: 'Email',
		required: true,
		error: 'emailError',
	},
	{
		id: 7,
		placeholder: 'Enter Residence Address',
		name: 'residenceAddress',
		type: 'text',
		label: 'Residence Address',
		required: true,
		error: 'residenceAddressError',
	},
	{
		id: 8,
		placeholder: 'Enter Phone Number',
		name: 'phoneNumber',
		type: 'tel',
		label: 'Phone Number',
		required: true,
		error: 'phoneNumberError',
	},
];

export const profileSelect = {
	language: [
		{ id: 1, name: 'English', value: 'English' },
		{ id: 2, name: 'French', value: 'French' },
		{ id: 3, name: 'Spanish', value: 'Spanish' },
		{ id: 4, name: 'Dutch', value: 'Dutch' },
		{ id: 5, name: 'Greek', value: 'Greek' },
	],
	preferredCurrency: [
		{ id: 1, name: 'Dollar', value: 'Dollars' },
		{ id: 2, name: 'Pound', value: 'Pounds' },
		{ id: 3, name: 'Franc', value: 'Amafaranga' },
		{ id: 4, name: 'Shilling', value: 'Shillings' },
	],
	gender: [
		{ id: 1, name: 'Male', value: 'Male' },
		{ id: 2, name: 'Female', value: 'Female' },
		{ id: 3, name: 'Neuter', value: 'Neuter' },
	],
};

export const profileTravelFields = [
	{
		id: 1,
		placeholder: 'Enter First Name',
		name: 'firstName',
		type: 'text',
		label: 'First Name',
		required: true,
		error: 'firstNameError',
	},
	{
		id: 2,
		placeholder: 'Enter Last Name',
		name: 'lastName',
		type: 'text',
		label: 'Last Name',
		required: true,
		error: 'lastNameError',
	},
	{
		id: 4,
		placeholder: 'Enter Department',
		name: 'department',
		type: 'text',
		label: 'department',
		required: true,
		error: 'departmentError',
	},
	{
		id: 7,
		placeholder: 'Enter Residence Address',
		name: 'residenceAddress',
		type: 'text',
		label: 'Residence Address',
		required: true,
		error: 'residenceAddressError',
	},
];
