export default {
	GET_USER_PROFILE_SUCCESS: 'GET_USER_PROFILE_SUCCESS',
	GET_USER_PROFILE_START: 'GET_USER_PROFILE_START',
	GET_USER_PROFILE_FAILURE: 'GET_USER_PROFILE_START',
	REVERT_CHANGES: 'REVERT_CHANGES',
	SET_EDIT_MODE: 'SET_EDIT_MODE',
	UPDATE_PROFILE: 'UPDATE_PROFILE',
	SAVE_PROFILE_START: 'SAVE_PROFILE_START',
	SAVE_PROFILE_SUCCESS: 'SAVE_PROFILE_SUCCESS',
	SAVE_PROFILE_FAILURE: 'SAVE_PROFILE_FAILURE',
};
